name: CI - Build and Test Service

on: [pull_request]
jobs:
  continuous-tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: run tests
      run: make run-tests
