name: CI - Build and Test Service

on: [pull_request]

env:
  DC: "CONTEXT=tests USER_ID=1000 GROUP_ID=1000 COMPOSE_REFERENCE_BRANCH=${{ github.ref_name }} docker compose -f ./dev/docker-compose.dev.yml"

jobs:
  continuous-tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v5

      - name: go fmt
        run: test -z $(gofmt -l .)

      - name: go vet
        run: go vet ./...

      - name: golint
        run: go install golang.org/x/lint/golint@latest && golint ./...

      - name: test
        run: go test -timeout 60s -race ./...
